--POPULATE DIMENSION, FACT, AND DATAMART

--DATE_DIM-----------------------------------------------------------------------------------------------
ALTER SESSION
SET
    WEEK_START = 0;
SET
    (START_DATE, END_DATE) = ('1995-01-01', '2025-01-01');
SET
    NUM_OF_DAYS = (
        SELECT
            DATEDIFF(DAY, TO_DATE($START_DATE), TO_DATE($END_DATE))
    );
CREATE
    OR REPLACE TABLE DATE_DIM as WITH DATE_DIM AS (
        SELECT
            ROW_NUMBER() OVER(
                ORDER BY
                    SEQ4()
            ) -1 AS DATE_DIM_ID,
            TO_DATE(DATEADD(DAY, DATE_DIM_ID, TO_DATE($START_DATE))) AS DATE
        FROM
            TABLE(GENERATOR(ROWCOUNT => $NUM_OF_DAYS))
    )
SELECT
    CONCAT(
        DATE_DIM_ID + 10,
        YEAR(DATE),
        TO_CHAR(DATE, 'MM'),
        TO_CHAR(DATE, 'DD')
    ) AS DATE_SK,
    DATE,
    DECODE(
        DAYNAME(DATE),
        'Mon',
        'Monday',
        'Tue',
        'Tuesday',
        'Wed',
        'Wednesday',
        'Thu',
        'Thursday',
        'Fri',
        'Friday',
        'Sat',
        'Saturday',
        'Sun',
        'Sunday'
    ) AS DAY_NAME,
    DAYNAME(DATE) AS DAY_NAME_ABV,
    DAYOFWEEK(DATE) DAY_OF_WEEK,
    MONTH(DATE) AS MONTH_NUM,
    CONCAT(YEAR(DATE), TO_CHAR(DATE, 'MM')) AS MONTH_ID,
    TO_CHAR(DATE, 'MMMM') AS MONTH_NAME,
    MONTHNAME(DATE) AS MONTH_NAME_ABV,
    DATEADD(DAY, 1, LAST_DAY(DATEADD(MONTH, -1, DATE), MONTH)) as First_Day_Month,
    LAST_DAY(DATE, MONTH) LAST_DAY_MONTH,
    QUARTER(DATE) AS QUARTER_NUM,
    CONCAT(YEAR(DATE), 'Q', QUARTER(DATE)) AS QUARTER_ID,
    DATEADD(
        DAY,
        1,
        LAST_DAY(DATEADD(QUARTER, -1, DATE), QUARTER)
    ) as FIRST_DAY_QUARTER,
    LAST_DAY(DATE, QUARTER) AS LAST_DAY_QUARTER,
    YEAR(DATE) AS YEAR
FROM
    DATE_DIM;
    
--CATEGORIES_DIM------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.CATEGORIES_DIM
SELECT
    CATEGORYID,
    CATEGORYNAME,
    DESCRIPTION,
    PICTURE
FROM
    PROJECT2.STAGING.CATEGORIES 

--CUSTOMERS_DIM-------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.CUSTOMERS_DIM
SELECT
    CUSTOMERID,
    COMPANYNAME,
    CONTACTNAME,
    CONTACTTITLE,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE,
    COUNTRY,
    PHONE,
    FAX
FROM
    PROJECT2.STAGING.CUSTOMERS 
    
--EMPLOYEES_DIM-----------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.EMPLOYEES_DIM
SELECT
    EMPLOYEEID,
    LASTNAME,
    FIRSTNAME,
    TITLE,
    TITLEOFCOURTESY,
    BIRTHDATE,
    HIREDATE,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE,
    COUNTRY,
    HOMEPHONE,
    EXTENSION,
    PHOTO,
    NOTES,
    REPORTSTO,
    PHOTOPATH
FROM
    PROJECT2.STAGING.EMPLOYEES 
    
--EMPLOYEE_TERRITORIES_DIM------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.EMPLOYEE_TERRITORIES_DIM
SELECT
    EMPLOYEEID,
    TERRITORYID
FROM
    PROJECT2.STAGING.EMPLOYEE_TERRITORIES 

--ORDERSHIP_DIM-----------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.ORDERSHIP_DIM
SELECT
    ORDERID,
    SHIPVIA,
    FREIGHT,
    SHIPNAME,
    SHIPADDRESS,
    SHIPCITY,
    SHIPREGION,
    SHIPPOSTALCODE,
    SHIPCOUNTRY
FROM
    PROJECT2.STAGING.ORDERS 

--PRODUCTS_DIM---------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.PRODUCTS_DIM
SELECT
    PRODUCTID,
    PRODUCTNAME,
    QUANTITYPERUNIT,
    UNITPRICE,
    UNITSINSTOCK,
    UNITSONORDER,
    REORDERLEVEL,
    DISCONTINUED
FROM
    PROJECT2.STAGING.PRODUCTS 
    
--REGIONS_DIM-----------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.REGIONS_DIM
SELECT
    REGIONID,
    REGIONDESCRIPTION
FROM
    PROJECT2.STAGING.REGIONS 
    
--SUPPLIERS_DIM-----------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.SUPPLIERS_DIM
SELECT
    SUPPLIERID,
    COMPANYNAME,
    CONTACTNAME,
    CONTACTTITLE,
    ADDRESS,
    CITY,
    REGION,
    POSTALCODE,
    COUNTRY,
    PHONE,
    FAX,
    HOMEPAGE
FROM
    PROJECT2.STAGING.SUPPLIERS 

--TERRITORIES_DIM----------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.TERRITORIES_DIM
SELECT
    TERRITORYID,
    TERRITORYDESCRIPTION,
    REGIONID
FROM
    PROJECT2.STAGING.TERRITORIES 

--COUNTRIES_DIM------------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.COUNTRIES_DIM
SELECT
    COUNTRYID,
    COUNTRYNAME,
    ALPHA2CODE,
    ALPHA3CODE
FROM
    PROJECT2.STAGING.COUNTRIES 

--FACT_ORDERS----------------------------------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.FACT_ORDERS
SELECT
    ORDERS.ORDERID,
    ORDERDETAIL.PRODUCTID,
    SUPPLIERS.SUPPLIERID,
    CATEGORIES.CATEGORYID,
    ORDERS.EMPLOYEEID,
    0 AS SHIPPERID,
    ORDERS.CUSTOMERID,
    COUNTRIES.COUNTRYID,
    ORDERS.ORDERDATE,
    ORDERS.REQUIREDDATE,
    ORDERS.SHIPPEDDATE,
    ORDERDETAIL.UNITPRICE,
    ORDERDETAIL.QUANTITY,
    ORDERDETAIL.DISCOUNT
FROM
    PROJECT2.STAGING.ORDERS ORDERS
    LEFT JOIN PROJECT2.STAGING.ORDER_DETAILS ORDERDETAIL ON ORDERS.ORDERID = ORDERDETAIL.ORDERID
    LEFT JOIN PROJECT2.STAGING.PRODUCTS PRODUCTS ON PRODUCTS.PRODUCTID = ORDERDETAIL.PRODUCTID
    LEFT JOIN PROJECT2.STAGING.SUPPLIERS SUPPLIERS ON SUPPLIERS.SUPPLIERID = PRODUCTS.SUPPLIERID
    LEFT JOIN PROJECT2.STAGING.CATEGORIES CATEGORIES ON CATEGORIES.CATEGORYID = PRODUCTS.CATEGORYID
    LEFT JOIN PROJECT2.STAGING.COUNTRIES COUNTRIES ON COUNTRIES.COUNTRYNAME = ORDERS.SHIPCOUNTRY 
    
--DATAMART_MONTHLY_SUPPLIER_GROSS_REVENUE------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.DATAMART_MONTHLY_SUPPLIER_GROSS_REVENUE
SELECT
    SUPPLIERS.COMPANYNAME,
    SUM(
        (
            ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
        ) * ORDERS.QUANTITY
    ) AS GROSS_REVENUE,
    DATES.YEAR,
    DATES.MONTH_NAME
FROM
    PROJECT2.DATAMART.FACT_ORDERS ORDERS
    LEFT JOIN PROJECT2.DATAMART.SUPPLIERS_DIM SUPPLIERS ON ORDERS.SUPPLIERID = SUPPLIERS.SUPPLIERID
    LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
    --WHERE DATES.YEAR=1996 AND DATES.MONTH_NAME='August'
GROUP BY
    SUPPLIERS.COMPANYNAME,
    DATES.YEAR,
    DATES.MONTH_NAME
ORDER BY
    DATES.YEAR,
    DATES.MONTH_NAME,
    SUPPLIERS.COMPANYNAME 
    
--DATAMART_MONTHLY_CATEGORY_SOLD----------------------------------------------------------------------------------------
DECLARE c1 CURSOR FOR
    SELECT
        DISTINCT MONTH_ID
    FROM
        PROJECT2.DATAMART.FACT_ORDERS ORDERS
    LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
    ORDER BY
        MONTH_ID DESC;
        
    monthid VARCHAR;
    
BEGIN 
    FOR record IN c1 DO 
        monthid := record.MONTH_ID;
        INSERT INTO
            PROJECT2.DATAMART.DATAMART_MONTHLY_CATEGORY_SOLD
        SELECT
            TOP 1 DATES.YEAR,
            DATES.MONTH_NAME,
            CATEGORIES.CATEGORYNAME,
            COUNT(CATEGORIES.CATEGORYNAME) AS QTY_CATEGORIES,
            SUM(ORDERS.QUANTITY) AS QTY_PRODUCT
        FROM
            PROJECT2.DATAMART.FACT_ORDERS ORDERS
            LEFT JOIN PROJECT2.DATAMART.PRODUCTS_DIM PRODUCTS ON ORDERS.PRODUCTID = PRODUCTS.PRODUCTID
            LEFT JOIN PROJECT2.DATAMART.CATEGORIES_DIM CATEGORIES ON CATEGORIES.CATEGORYID = ORDERS.CATEGORYID
            LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
        WHERE
            DATES.MONTH_ID = :monthid
        GROUP BY
            CATEGORIES.CATEGORYNAME,
            DATES.YEAR,
            DATES.MONTH_NAME,
            DATES.MONTH_ID
        ORDER BY
            DATES.YEAR,
            DATES.MONTH_NAME,
            COUNT(CATEGORIES.CATEGORYNAME) DESC;
    END FOR;
RETURN 'End';
END;

--DATAMART_DAILY_GROSS_REVENUE---------------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.DATAMART_DAILY_GROSS_REVENUE
SELECT
    DATES.DATE,
    DATES.MONTH_NAME,
    DATES.YEAR,
    SUM(
        (
            ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
        ) * ORDERS.QUANTITY
    ) AS GROSS_REVENUE
FROM
    PROJECT2.DATAMART.FACT_ORDERS ORDERS
    LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
GROUP BY
    DATES.DATE,
    DATES.MONTH_NAME,
    DATES.YEAR
ORDER BY
    DATES.DATE DESC 

--DATAMART_MONTHLY_BEST_EMPLOYEES-------------------------------------------------------------------------------
DECLARE c1 CURSOR FOR
    SELECT
        DISTINCT MONTH_ID
    FROM
        PROJECT2.DATAMART.FACT_ORDERS ORDERS
    LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
    ORDER BY
        MONTH_ID DESC;
        
    monthid VARCHAR;
    
BEGIN 
    FOR record IN c1 DO 
        monthid := record.MONTH_ID;
        INSERT INTO
            PROJECT2.DATAMART.DATAMART_MONTHLY_BEST_EMPLOYEES
        SELECT
            TOP 1 DATES.YEAR,
            DATES.MONTH_NAME,
            CONCAT(
                EMPLOYEES.TITLEOFCOURTESY,
                ' ',
                EMPLOYEES.FIRSTNAME,
                ' ',
                EMPLOYEES.LASTNAME
            ) AS EMPLOYEE_NAME,
            SUM(
                (
                    ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
                ) * ORDERS.QUANTITY
            ) AS GROSS_REVENUE
        FROM
            PROJECT2.DATAMART.FACT_ORDERS ORDERS
        LEFT JOIN PROJECT2.DATAMART.EMPLOYEES_DIM EMPLOYEES ON ORDERS.EMPLOYEEID = EMPLOYEES.EMPLOYEEID
        LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
        WHERE
            DATES.MONTH_ID = :monthid
        GROUP BY
            DATES.YEAR,
            DATES.MONTH_NAME,
            EMPLOYEES.TITLEOFCOURTESY,
            EMPLOYEES.FIRSTNAME,
            EMPLOYEES.LASTNAME
        ORDER BY
            SUM(
                (
                    ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
                ) * ORDERS.QUANTITY
            ) DESC;
    END FOR;
RETURN 'End';
END;

--DATAMART_MONTHLY_COUNTRY_GROSS_REVENUE---------------------------------------------------------------------------
INSERT INTO
    PROJECT2.DATAMART.DATAMART_MONTHLY_COUNTRY_GROSS_REVENUE
SELECT
    DATES.MONTH_ID,
    DATES.YEAR,
    DATES.MONTH_NAME,
    COUNTRIES.COUNTRYNAME AS COUNTRY_NAME,
    SUM(
        (
            ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
        ) * ORDERS.QUANTITY
    ) AS GROSS_REVENUE
FROM
    PROJECT2.DATAMART.FACT_ORDERS ORDERS
    LEFT JOIN PROJECT2.DATAMART.COUNTRIES_DIM COUNTRIES ON ORDERS.COUNTRYID = COUNTRIES.COUNTRYID
    LEFT JOIN PROJECT2.DATAMART.DATE_DIM DATES ON DATES.DATE = ORDERS.ORDERDATE
GROUP BY
    DATES.MONTH_ID,
    DATES.YEAR,
    DATES.MONTH_NAME,
    COUNTRIES.COUNTRYNAME
ORDER BY
    DATES.MONTH_ID DESC,
    SUM(
        (
            ORDERS.UNITPRICE - (ORDERS.UNITPRICE * ORDERS.DISCOUNT)
        ) * ORDERS.QUANTITY
    ) DESC;